module Products
  module ProductListingData
    def self.product_listing
      {
        "memberships": [],
        "memberships_pagination": {
          "page": 1,
          "pages": 1,
        },
        "products": [
          {
            "id": 5624454,
            "edit_url": "/products/xplitr/edit",
            "is_duplicating": false,
            "is_unpublished": true,
            "name": "digital product",
            "permalink": "xplitr",
            "price_formatted": "CAD$27",
            "revenue": 0.0,
            "status": "unpublished",
            "thumbnail": nil,
            "display_price_cents": 2700,
            "url": "https://jdesma.gumroad.com/l/xplitr-xplitr-xplitr-xplitr2",
            "url_without_protocol": "jdesma.gumroad.com/l/xplitr-xplitr-xplitr-xplitr2",
            "has_duration": false,
            "can_edit": true,
            "can_destroy": true,
            "can_duplicate": true,
            "can_archive": true,
            "can_unarchive": false,
            "successful_sales_count": 0,
            "remaining_for_sale_count": nil,
            "monthly_recurring_revenue": 0.0,
            "revenue_pending": 0.0,
          },
          {
            "id": 5613022,
            "edit_url": "/products/nteiqo/edit",
            "is_duplicating": false,
            "is_unpublished": true,
            "name": "product name",
            "permalink": "nteiqo",
            "price_formatted": "$100",
            "revenue": 0.0,
            "status": "unpublished",
            "thumbnail": nil,
            "display_price_cents": 10000,
            "url": "https://jdesma.gumroad.com/l/nteiqo",
            "url_without_protocol": "jdesma.gumroad.com/l/nteiqo",
            "has_duration": false,
            "can_edit": true,
            "can_destroy": true,
            "can_duplicate": true,
            "can_archive": true,
            "can_unarchive": false,
            "successful_sales_count": 0,
            "remaining_for_sale_count": nil,
            "monthly_recurring_revenue": 0.0,
            "revenue_pending": 0.0,
          },
          {
            "id": 5612932,
            "edit_url": "/products/davpc/edit",
            "is_duplicating": false,
            "is_unpublished": true,
            "name": "Product Name",
            "permalink": "davpc",
            "price_formatted": "$100",
            "revenue": 0.0,
            "status": "unpublished",
            "thumbnail": nil,
            "display_price_cents": 10000,
            "url": "https://jdesma.gumroad.com/l/davpc",
            "url_without_protocol": "jdesma.gumroad.com/l/davpc",
            "has_duration": false,
            "can_edit": true,
            "can_destroy": true,
            "can_duplicate": true,
            "can_archive": true,
            "can_unarchive": false,
            "successful_sales_count": 0,
            "remaining_for_sale_count": nil,
            "monthly_recurring_revenue": 0.0,
            "revenue_pending": 0.0,
          },
          {
            "id": 5597013,
            "edit_url": "/products/nfxka/edit",
            "is_duplicating": false,
            "is_unpublished": true,
            "name": "Digital Product 1",
            "permalink": "nfxka",
            "price_formatted": "CAD$100",
            "revenue": 0.0,
            "status": "unpublished",
            "thumbnail": nil,
            "display_price_cents": 10000,
            "url": "https://jdesma.gumroad.com/l/nfxka",
            "url_without_protocol": "jdesma.gumroad.com/l/nfxka",
            "has_duration": false,
            "can_edit": true,
            "can_destroy": true,
            "can_duplicate": true,
            "can_archive": true,
            "can_unarchive": false,
            "successful_sales_count": 0,
            "remaining_for_sale_count": nil,
            "monthly_recurring_revenue": 0.0,
            "revenue_pending": 0.0,
          },
          {
            "id": 5590099,
            "edit_url": "/products/aqqtt/edit",
            "is_duplicating": false,
            "is_unpublished": true,
            "name": "test001",
            "permalink": "aqqtt",
            "price_formatted": "$1",
            "revenue": 0.0,
            "status": "unpublished",
            "thumbnail": nil,
            "display_price_cents": 100,
            "url": "https://jdesma.gumroad.com/l/aqqtt",
            "url_without_protocol": "jdesma.gumroad.com/l/aqqtt",
            "has_duration": false,
            "can_edit": true,
            "can_destroy": true,
            "can_duplicate": true,
            "can_archive": true,
            "can_unarchive": false,
            "successful_sales_count": 0,
            "remaining_for_sale_count": nil,
            "monthly_recurring_revenue": 0.0,
            "revenue_pending": 0.0,
          },
          {
            "id": 5579264,
            "edit_url": "/products/qxwqj/edit",
            "is_duplicating": false,
            "is_unpublished": true,
            "name": "bundle",
            "permalink": "qxwqj",
            "price_formatted": "CAD$999",
            "revenue": 0.0,
            "status": "unpublished",
            "thumbnail": nil,
            "display_price_cents": 99900,
            "url": "https://jdesma.gumroad.com/l/qxwqj",
            "url_without_protocol": "jdesma.gumroad.com/l/qxwqj",
            "has_duration": false,
            "can_edit": true,
            "can_destroy": true,
            "can_duplicate": true,
            "can_archive": true,
            "can_unarchive": false,
            "successful_sales_count": 0,
            "remaining_for_sale_count": nil,
            "monthly_recurring_revenue": 0.0,
            "revenue_pending": 0.0,
          },
          {
            "id": 5579261,
            "edit_url": "/products/hjfsgh/edit",
            "is_duplicating": false,
            "is_unpublished": true,
            "name": "physical_good",
            "permalink": "hjfsgh",
            "price_formatted": "CAD$999",
            "revenue": 0.0,
            "status": "unpublished",
            "thumbnail": nil,
            "display_price_cents": 99900,
            "url": "https://jdesma.gumroad.com/l/hjfsgh",
            "url_without_protocol": "jdesma.gumroad.com/l/hjfsgh",
            "has_duration": false,
            "can_edit": true,
            "can_destroy": true,
            "can_duplicate": true,
            "can_archive": true,
            "can_unarchive": false,
            "successful_sales_count": 0,
            "remaining_for_sale_count": nil,
            "monthly_recurring_revenue": 0.0,
            "revenue_pending": 0.0,
          },
          {
            "id": 5579245,
            "edit_url": "/products/bzygfd/edit",
            "is_duplicating": false,
            "is_unpublished": true,
            "name": "ebook",
            "permalink": "bzygfd",
            "price_formatted": "CAD$999",
            "revenue": 0.0,
            "status": "unpublished",
            "thumbnail": nil,
            "display_price_cents": 99900,
            "url": "https://jdesma.gumroad.com/l/bzygfd",
            "url_without_protocol": "jdesma.gumroad.com/l/bzygfd",
            "has_duration": false,
            "can_edit": true,
            "can_destroy": true,
            "can_duplicate": true,
            "can_archive": true,
            "can_unarchive": false,
            "successful_sales_count": 0,
            "remaining_for_sale_count": nil,
            "monthly_recurring_revenue": 0.0,
            "revenue_pending": 0.0,
          },
          {
            "id": 5579242,
            "edit_url": "/products/wesnc/edit",
            "is_duplicating": false,
            "is_unpublished": true,
            "name": "course",
            "permalink": "wesnc",
            "price_formatted": "CAD$999",
            "revenue": 0.0,
            "status": "unpublished",
            "thumbnail": nil,
            "display_price_cents": 99900,
            "url": "https://jdesma.gumroad.com/l/wesnc",
            "url_without_protocol": "jdesma.gumroad.com/l/wesnc",
            "has_duration": false,
            "can_edit": true,
            "can_destroy": true,
            "can_duplicate": true,
            "can_archive": true,
            "can_unarchive": false,
            "successful_sales_count": 0,
            "remaining_for_sale_count": nil,
            "monthly_recurring_revenue": 0.0,
            "revenue_pending": 0.0,
          },
          {
            "id": 5579232,
            "edit_url": "/products/gxtwf/edit",
            "is_duplicating": false,
            "is_unpublished": true,
            "name": "digital product",
            "permalink": "gxtwf",
            "price_formatted": "CAD$999",
            "revenue": 0.0,
            "status": "unpublished",
            "thumbnail": nil,
            "display_price_cents": 99900,
            "url": "https://jdesma.gumroad.com/l/gxtwf",
            "url_without_protocol": "jdesma.gumroad.com/l/gxtwf",
            "has_duration": false,
            "can_edit": true,
            "can_destroy": true,
            "can_duplicate": true,
            "can_archive": true,
            "can_unarchive": false,
            "successful_sales_count": 0,
            "remaining_for_sale_count": nil,
            "monthly_recurring_revenue": 0.0,
            "revenue_pending": 0.0,
          },
        ],
        "products_pagination": {
          "page": 1,
          "pages": 1,
        },
        "archived_products_count": 0,
        "collabs_enabled": true,
        "can_create_product": true,
      }
    end
  end
end
