# https://docs.docker.com/reference/
version: '3.4'

services:
  appserver:
    build:
      context: ./server
      dockerfile: ../docker-compose/app/Dockerfile
    ports:
      - 8000:3000
      - 3035:3035
    volumes:
      - ./server:/app
    tmpfs:
      - /tmp
    working_dir: /app
    user: appserver
    command: ./bin/dev

  db:
    image: mysql:8.0.36-debian
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer:4.8.1-standalone # https://hub.docker.com/_/adminer
    restart: always
    ports:
      - 8001:8080
  
  www:
    image: nginx:bookworm
    ports:
      - 8080:80
    volumes:
      - ./docker-compose/www/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./webflow/export:/usr/share/nginx/html

volumes:
  db-data:
