#
# for testing the production build locally (see README)
#

# https://docs.docker.com/reference/
version: '3.4'

services:
  appserver-staging:
    build:
      context: ./webapp
      dockerfile: ../linode/app/Dockerfile
    ports:
      - 8000:3000
    env_file: ./.env-staging
    command: ./bin/rails server
    networks:
      - staging

  db:
    image: mysql:8.0.36-debian
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc
    volumes:
      - staging-db-data:/var/lib/mysql
    networks:
      - staging

  adminer:
    image: adminer:4.8.1-standalone # https://hub.docker.com/_/adminer
    restart: always
    ports:
      - 8001:8080
    networks:
      - staging
  
  www:
    image: nginx:bookworm
    ports:
      - 8080:80
    volumes:
      - ./docker-compose/www/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./webflow/export:/usr/share/nginx/html
    networks:
      - staging

  smoke-test-runner:
    build:
      context: ./smoke-test-runner
      dockerfile: ../docker-compose/app/Dockerfile
    volumes:
      - ./smoke-test-runner:/app
    tmpfs:
      - /tmp
    working_dir: /app
    command: sh -c 'while :; do sleep .5; done'
    stop_signal: SIGINT
    networks:
      - staging

  selenium-standalone:
    image: selenium/standalone-chrome:4.18.1-20240224 # https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#standalone
    ports:
      - 4444:4444
    shm_size: 2g # https://docs.docker.com/compose/compose-file/05-services/#shm_size
    networks:
      - staging

volumes:
  staging-db-data:

networks:
  staging:
