# syntax = docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=3.3.0
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim as base

# Install packages needed to build gems
# RUN apt-get update -qq && \
#     apt-get install --no-install-recommends -y procps inetutils-ping tinysshd
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y procps inetutils-ping dropbear dropbear-bin curl xz-utils

# Entrypoint prepares the database.
# ENTRYPOINT ["/rails/bin/docker-entrypoint"]

# Start the server by default, this can be overwritten at runtime
EXPOSE 22
# CMD ["./bin/rails", "server"]

COPY Dsshd-entrypoint.sh /
ENTRYPOINT ["/Dsshd-entrypoint.sh"]

COPY id_rsa.pub /root/.ssh/authorized_keys
# COPY id_ed25519.pub /root/.ssh/authorized_keys
RUN chmod 700 /root/.ssh
RUN chmod 600 /root/.ssh/authorized_keys

COPY z/aws /root/aws
RUN cd /root && aws/install

COPY Dsshd-aws-config /root/.aws/config
RUN chmod 600 ~/.aws/config
