# https://docs.docker.com/reference/
version: '3.4'

services:
  appserver:
    build:
      context: .
      dockerfile: ./Dockerfile-prod
      args:
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    ports:
      - 8000:3000
      - 3035:3035
    tmpfs:
      - /tmp
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    user: rails
    # command: sh -c 'while :; do sleep .5; done'
    # stop_signal: SIGINT
    command: ./bin/rails server

  db:
    image: mysql:8.0.36-debian
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer:4.8.1-standalone # https://hub.docker.com/_/adminer
    restart: always
    ports:
      - 8001:8080

volumes:
  db-data:
