# syntax = docker/dockerfile:1

# https://hub.docker.com/_/nginx
# https://github.com/nginxinc/docker-nginx/tree/1f227619c1f1baa0bed8bed844ea614437ff14fb/mainline/debian
FROM nginx:bookworm

COPY . /usr/share/nginx/html
RUN mv /usr/share/nginx/html/index-production.html /usr/share/nginx/html/index.html
