# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

# Finding and customizing actions:
# https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions

name: Test & Deploy to Amazon ECS

on:
  push:
    tags:
      - deploy-*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        env:
          IMAGE: test:${{ github.sha }}
        run: |
          docker build -f github-workflows/Dockerfile -t $IMAGE ./webapp
          docker run --rm --volume ./webapp:/app --workdir /app --user runner --env CI=true $IMAGE yarn install
          docker run --rm --volume ./webapp:/app --workdir /app --user runner --env CI=true $IMAGE ./node_modules/.bin/jest
          docker run --rm --volume ./webapp:/app --workdir /app --user runner --env CI=true $IMAGE ./bin/rails test
          docker run --rm --volume ./webapp:/app --workdir /app --user runner --env CI=true $IMAGE ./bin/rails test:system

  deploy-staging:
    name: Deploy to staging
    needs: test
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout
        uses: appleboy/ssh-action@v1.0.3 # https://github.com/marketplace/actions/ssh-remote-commands
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd gumroad-jd
            git fetch --all
            git checkout ${{ github.sha }}

      - name: Build
        uses: appleboy/ssh-action@v1.0.3 # https://github.com/marketplace/actions/ssh-remote-commands
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd gumroad-jd
            source .env-linode-staging
            export RAILS_MASTER_KEY
            docker compose -f docker-compose-linode-staging.yml build appserver-linode-staging

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3 # https://github.com/marketplace/actions/ssh-remote-commands
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd gumroad-jd
            docker compose -f docker-compose-linode-staging.yml down appserver-linode-staging
            docker compose -f docker-compose-linode-staging.yml up -d appserver-linode-staging

  smoke-test:
    name: Smoke test staging
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run smoke test
        env:
          IMAGE: smoke-test-runner:${{ github.sha }}
        run: |
          docker build -f github-workflows/Dockerfile -t $IMAGE ./smoke-test-runner
          NETWORK=$(docker network ls --format '{{ .Name }}' --filter name=github_network)
          echo "NETWORK is: $NETWORK"
          docker run --rm --volume ./smoke-test-runner:/app --workdir /app --user runner --network $(docker network ls --format '{{ .Name }}' --filter name=github_network) $IMAGE ./bin/rails test:system

    services:
      selenium-standalone:
        image: selenium/standalone-chrome:4.18.1-20240224
        options: --shm-size=2gb # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontaineroptions
        ports:
          - 4444:4444

  deploy-production:
    name: Deploy to production
    needs: smoke-test
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Build
        uses: appleboy/ssh-action@v1.0.3 # https://github.com/marketplace/actions/ssh-remote-commands
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd gumroad-jd
            source .env-linode-production
            export RAILS_MASTER_KEY
            docker compose -f docker-compose-linode-production.yml build appserver-linode-production

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3 # https://github.com/marketplace/actions/ssh-remote-commands
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd gumroad-jd
            docker compose -f docker-compose-linode-production.yml down appserver-linode-production
            docker compose -f docker-compose-linode-production.yml up -d appserver-linode-production
