# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

# Finding and customizing actions:
# https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions
# https://github.com/marketplace

name: Test

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout
        uses: appleboy/ssh-action@v1.0.3 # https://github.com/marketplace/actions/ssh-remote-commands
        env:
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd gumroad-jd-test
            git fetch --all
            git checkout $SHA

      - name: Build
        uses: appleboy/ssh-action@v1.0.3 # https://github.com/marketplace/actions/ssh-remote-commands
        env:
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd gumroad-jd-test
            docker build -f github-workflows/Dockerfile -t test:$SHA ./webapp
            docker run --rm --volume ./webapp:/app --workdir /app --user runner --env CI=true test:$SHA yarn install

  test-jest:
    name: Run Jest Tests
    needs: build
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Run tests
        uses: appleboy/ssh-action@v1.0.3 # https://github.com/marketplace/actions/ssh-remote-commands
        env:
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd gumroad-jd-test
            docker run --rm --volume ./webapp:/app --workdir /app --user runner --env CI=true test:$SHA ./node_modules/.bin/jest

  test-rails-test:
    name: Run rails test
    needs: build
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Run tests
        uses: appleboy/ssh-action@v1.0.3 # https://github.com/marketplace/actions/ssh-remote-commands
        env:
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd gumroad-jd-test
            docker run --rm --volume ./webapp:/app --workdir /app --user runner --env CI=true test:$SHA ./bin/rails test

  test-rails-test-system:
    name: Run rails test:system
    needs: build
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Run tests
        uses: appleboy/ssh-action@v1.0.3 # https://github.com/marketplace/actions/ssh-remote-commands
        env:
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd gumroad-jd-test
            docker run --rm --volume ./webapp:/app --workdir /app --user runner --env CI=true test:$SHA ./bin/rails test:system
